# Analise Preditiva de churn

## Sobre o Dataset

Para o nosso projeto usaremos uma base de churn,  essa base se diz respeito a serviços de internet, telefone e tv - Telecomunicação.

Vamos realizar aqui as EDA.

Legenda dos dados:

*   **CustomerID** : Esse é o ID único de cada cliente nosso da rede de produtos de telecomunicação.

*   **Genero** : O genero dos nossos clientes.

*   **Idoso** : Se nosso cliente tem acima de 60 anos ou não. (Sim = 1 | Não = 0)

*   **Casado** : Se nosso cliente é casado ou não.

*   **Dependents** : Se cliente tem dependentes.

*   **Tempo_como_Cliente** : Tempo em meses que nosso cliente está com a nossa empresa.

*   **PhoneService** : Se ele contratou serviço telefônico com a nossa empresa.

*   **Servico_Internet** : Qual o tipo de serviço de internet contratado.

*   **Servico_Seguranca** : Se ele contratou serviço de segurança com a nossa empresa.

*   **Suporte_Tecnico** : Se já acionou o suporte técnico.

*   **StreamingTV** : Se ele contratou serviço de streaming para TV.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **PaymentMethod** : Forma de Pagamento.

*   **Pagamento_Mensal** : Quanto o cliente pagava mensalmente.

*   **Total_Pago** : Total já pago pelo cliente para nossa companhia.

*   **Churn** : Nossa coluna mais importante, se nosso cliente nos abandonou ou não.

## Objetivo

## Ferramentas

In [17]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [18]:
df = pd.read_csv("data.csv", delimiter=';')

df.head(10)

  customerid,genero,idoso,casado,dependents,tempo_como_cliente,servico_internet,servico_seguranca,suporte_tecnico,streamingtv,tipo_contrato,paymentmethod,pagamento_mensal,total_pago,churn
0  7590-VHVEG,F,False,True,True,1,DSL,No,No,No,Mo...
1  5575-GNVDE,M,False,True,True,34,DSL,Yes,No,No,...
2  3668-QPYBK,M,False,True,True,2,DSL,Yes,No,No,M...
3  7795-CFOCW,M,False,True,True,45,DSL,Yes,Yes,No...
4  8191-XWSZG,,False,True,True,52,No,No internet ...
5  9959-WOFKT,M,False,True,True,71,Fiber optic,Ye...
6  4190-MFLUW,,False,True,True,10,DSL,No,Yes,No,M...
7  4183-MYFRB,,False,True,True,21,Fiber optic,No,...
8  8779-QRDMV,M,True,True,True,1,DSL,No,No,No,Mon...
9  1680-VDCWW,M,False,True,True,12,No,No internet...

# Etapa 1 - EDA

In [19]:
#seu código aqui
df.dtypes

customerid,genero,idoso,casado,dependents,tempo_como_cliente,servico_internet,servico_seguranca,suporte_tecnico,streamingtv,tipo_contrato,paymentmethod,pagamento_mensal,total_pago,churn    str
dtype: object

In [20]:
colunas = ['Idoso', 'Casado', 'Dependents', 'Churn']

for i in colunas:
    df[i] = df[i].astype(bool)

KeyError: 'Idoso'

In [5]:
df.dtypes

customerID                str
Genero                    str
Idoso                    bool
Casado                   bool
Dependents               bool
Tempo_como_Cliente      int64
PhoneService              str
Servico_Internet          str
Servico_Seguranca         str
Suporte_Tecnico           str
StreamingTV               str
Tipo_Contrato             str
PaymentMethod             str
Pagamento_Mensal      float64
Total_Pago            float64
Churn                    bool
dtype: object

In [6]:
df.isnull().mean()*100

customerID             0.00
Genero                 0.48
Idoso                  0.00
Casado                 0.00
Dependents             0.00
Tempo_como_Cliente     0.00
PhoneService          59.28
Servico_Internet       0.00
Servico_Seguranca      0.00
Suporte_Tecnico        0.00
StreamingTV            0.00
Tipo_Contrato          0.00
PaymentMethod          0.00
Pagamento_Mensal      13.00
Total_Pago             0.00
Churn                  0.00
dtype: float64

In [7]:
df.describe()

       Tempo_como_Cliente  Pagamento_Mensal   Total_Pago
count         2500.000000       2175.000000  2500.000000
mean            32.341600         65.607563  2291.882880
std             24.626398         29.931520  2265.347752
min              0.000000         18.400000    18.800000
25%              8.000000         39.500000   402.337500
50%             29.000000         71.450000  1405.325000
75%             56.000000         90.250000  3867.162500
max             72.000000        118.650000  8564.750000

### Tratamento de dados nulos

Optei por deletar a coluna [PhoneService],  pois aferindo que nao possui relevancia significativa para a nossa analise, alem disso se trata de uma coluna boleana, por padrao os dados nulos seriam preenchidos com false, mas isso tornaria minha analise enviesada e com possiveis outliers pelo alta quantidade de dados nulos.

In [8]:
df['PhoneService'].unique()

<StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [21]:
df = df.drop('PhoneService', axis=1)

KeyError: "['PhoneService'] not found in axis"

Indo para a coluna [Pagamento mensal] podemos observar que se trata de uma coluna com poucos dados faltantes, representando 13% de todo conjunto, e a media nao e discrepante em relacao aos valores maximos e minimos como pudemos observar pela funcao describe. Por se tratar de uma coluna importante para analise, pois o pagamento pode influenciar na presenca ou saida do cliente optei por preencher os valores nulos pela media da coluna.

In [10]:
df['Pagamento_Mensal'].describe()
df['Pagamento_Mensal'] = df['Pagamento_Mensal'].fillna(df['Pagamento_Mensal'].mean())

Sobre a coluna [Genero] ela tem um numero insigficante de valores nulos representando apenas 0.48% isso equivalore a apenas 12 linhas. Logo aferi que a quantidade de valores nulos e extremamente insignificante na coluna genero, alem disso nao se trata de uma analise que o genero impacta substancialmente, por isso optei em apagar as linhas que contem os valores nulos.

In [22]:
df = df.dropna(subset=['Genero'])
df['Genero'].isnull().sum()

KeyError: ['Genero']

In [23]:
# Padronizando os valores categoricos
df['Genero'].unique()
mapa = {'Female' : 'F', 'Male': 'M', 'f': 'F'}
df['Genero'] = df['Genero'].map(mapa)

KeyError: 'Genero'

In [24]:
# Padronizando colunas
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [25]:
df

     customerid,genero,idoso,casado,dependents,tempo_como_cliente,servico_internet,servico_seguranca,suporte_tecnico,streamingtv,tipo_contrato,paymentmethod,pagamento_mensal,total_pago,churn
0     7590-VHVEG,F,False,True,True,1,DSL,No,No,No,Mo...
1     5575-GNVDE,M,False,True,True,34,DSL,Yes,No,No,...
2     3668-QPYBK,M,False,True,True,2,DSL,Yes,No,No,M...
3     7795-CFOCW,M,False,True,True,45,DSL,Yes,Yes,No...
4     8191-XWSZG,,False,True,True,52,No,No internet ...
...                                                 ...
2483  6188-UXBBR,F,False,True,True,38,No,No internet...
2484  2333-KWEWW,M,False,True,True,18,No,No internet...
2485  5702-SKUOB,F,False,True,True,4,No,No internet ...
2486  1134-YWTYF,M,False,True,True,27,DSL,No,Yes,No,...
2487  6061-GWWAV,M,False,True,True,41,DSL,Yes,No,Yes...

[2488 rows x 1 columns]

In [26]:
df.to_csv("data_EDA.csv", index=False)